builders:
  api_index:
    import: 'package:jaspr_content_snippets/builders.dart'
    build_to: cache
    builder_factories: ['DartIndexBuilder.new']
    auto_apply: all_packages
    runs_before: [jaspr_content_snippets]
    build_extensions: {"lib/lib": ['api.json']}

  jaspr_content_snippets:
    import: 'package:jaspr_content_snippets/builders.dart'
    build_to: cache
    builder_factories: ['excerptsBuilder']
    auto_apply: none
    build_extensions: {'': ['.snippet.json']}
    defaults:
      options:
        process_without_directives: false