name: jaspr_content_snippets
description: External content snippets for `jaspr_content` sites.
version: 0.1.2
repository: https://github.com/simolus3/goodies.dart/tree/main/jaspr_content_snippets
issue_tracker: https://github.com/simolus3/goodies.dart/issues

environment:
  sdk: ^3.9.0

topics:
  - jaspr
  - analyzer
  - build

dependencies:
  _fe_analyzer_shared: ^89.0.0
  analyzer: ^8.2.0
  analyzer_plugin: ^0.13.8
  build: ^4.0.0
  build_config: ^1.2.0
  collection: ^1.19.1
  glob: ^2.1.3
  jaspr: ^0.21.3
  jaspr_content: ^0.4.1
  logging: ^1.3.0
  meta: ^1.17.0
  path: ^1.9.1
  source_span: ^1.10.1
  sqlparser: ^0.41.2
  syntax_highlight_lite: ^0.0.1
  universal_web: ^1.1.1
  yaml: ^3.1.3

dev_dependencies:
  build_runner: ^2.8.0
  build_test: ^3.4.1
  jaspr_test: ^0.21.3
  lints: ^6.0.0
  shelf: ^1.4.2
  test: ^1.25.6
