name: locks
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.2

# Add regular dependencies here.
dependencies:
  ffi: ^2.1.4
  hooks: ^0.20.0
  code_assets: ^0.19.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
