name: shelf_multipart
description: shelf_multipart parses multipart and form-data requests for shelf handlers.
version: 2.0.1
repository: https://github.com/simolus3/goodies.dart/tree/main/shelf_multipart
issue_tracker: https://github.com/simolus3/goodies.dart/issues

environment:
  sdk: '^3.3.0'

dependencies:
  http_parser: ^4.0.0
  mime: '>=1.0.0 <3.0.0'
  shelf: ^1.0.0
  string_scanner: ^1.1.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.16.0
