[target.x86_64-unknown-linux-gnu]
linker = "x86_64-linux-gnu-gcc"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabi-gcc"

[target.riscv64gc-unknown-linux-gnu]
linker = "riscv64-linux-gnu-gcc"

[target.aarch64-linux-android]
rustflags = [
    "-C", "link-arg=-Wl,-soname,libdart_locks.so",
]

[target.armv7-linux-androideabi]
rustflags = [
    "-C", "link-arg=-Wl,-soname,libdart_locks.so",
]

[target.x86_64-linux-android]
rustflags = [
    "-C", "link-arg=-Wl,-soname,libdart_locks.so",
]
