name: CI

on:
  push:
    branches: [ main, locks ]
  pull_request:
    branches: [ main ]
  schedule:
    # Make sure everything is still working by running the CI weekly.
    - cron: "0 5 * * 1"

jobs:
  compile_native_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-unknown-linux-gnu,x86_64-unknown-linux-gnu,riscv64gc-unknown-linux-gnu,armv7-unknown-linux-gnueabihf,aarch64-linux-android,armv7-linux-androideabi,x86_64-linux-android
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-ndk

      - name: Build x64
        working-directory: locks/native
        run: cargo build --release --target x86_64-unknown-linux-gnu
      - name: Build aarch64
        working-directory: locks/native
        run: cargo build --release --target aarch64-unknown-linux-gnu
      - name: Build armv7
        working-directory: locks/native
        run: cargo build --release --target armv7-unknown-linux-gnueabihf
      - name: Build riscv64gc
        working-directory: locks/native
        run: cargo build --release --target riscv64gc-unknown-linux-gnu
      - name: Build Android libs
        working-directory: locks/native
        run: cargo ndk -t armeabi-v7a -t arm64-v8a -t x86_64 --release -o target/android

  compile_native_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin,aarch64-apple-darwin,aarch64-apple-ios,aarch64-apple-ios-sim,x86_64-apple-ios
      - name: Build macOS
        working-directory: locks/native
        run: |
          cargo build --release --target x86_64-apple-darwin
          cargo build --release --target aarch64-apple-darwin
      - name: Build iOS
        working-directory: locks/native
        run: |
          cargo build --release --target aarch64-apple-ios
          cargo build --release --target aarch64-apple-ios-sim
          cargo build --release --target x86_64-apple-ios

  compile_native_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc,aarch64-pc-windows-msvc
      - name: Build Windows
        working-directory: locks/native
        run: |
          cargo build --release --target x86_64-pc-windows-msvc
          cargo build --release --target aarch64-pc-windows-msvc

  setup:
    runs-on: ubuntu-latest
    outputs:
      dart-version: ${{ steps.setup-dart.outputs.dart-version }}
      cache-key: dart-packages-${{ steps.deps-after.outputs.lockfiles }}
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        id: setup-dart
        with:
          sdk: beta
      - uses: actions/cache/restore@v4
        with:
          path: |
            ${{ env.PUB_CACHE }}
            shelf_multipart/pubspec.lock
            locks/pubspec.lock
          # We can only use fallback keys here since we don't know the lockfile contents yet.
          key: dart-packages-stub
          restore-keys: |
            dart-packages-

      - name: "Hash pubspec lockfiles before pub upgrade"
        id: deps-before
        run: |
          echo "lockfiles=${{ hashFiles('**/pubspec.lock') }}" >> $GITHUB_OUTPUT
      - name: Install dependencies
        run: |-
          pushd shelf_multipart
          dart pub upgrade
          popd
          pushd locks
          dart pub upgrade
          popd
      - name: "Hash pubspec lockfiles after pub upgrade"
        id: deps-after
        run: |
          echo "lockfiles=${{ hashFiles('**/pubspec.lock') }}" >> $GITHUB_OUTPUT

      - name: "Update cache due to changed pubspec.lock"
        if: ${{ !failure() && ( steps.deps-after.outputs.lockfiles != steps.deps-before.outputs.lockfiles) }}
        uses: actions/cache/save@v4
        with:
          path: |
            ${{ env.PUB_CACHE }}
            shelf_multipart/pubspec.lock
            locks/pubspec.lock
          key: dart-packages-${{ steps.deps-after.outputs.lockfiles }}

  shelf_multipart:
    runs-on: ubuntu-latest
    needs: setup
    defaults:
      run:
        working-directory: shelf_multipart

    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ needs.setup.outputs.dart-version }}
      - uses: actions/cache/restore@v4
        with:
          path: |
            ${{ env.PUB_CACHE }}
            shelf_multipart/pubspec.lock
          key: ${{ needs.setup.outputs.cache-key }}
          fail-on-cache-miss: true
      - name: Install dependencies
        run: dart pub get --offline
      - name: Verify format
        run: dart format --output=none --set-exit-if-changed .
      - name: Analyze project
        run: dart analyze --fatal-infos
      - name: Run tests
        run: dart test
